### ISSUE TITLE
Bij aanmaken statustype in admin scherm: Sorry, a server error has occurred (500)

### ISSUE THREAD

**Issue by mvturnho** [VNG-Realisatie/gemma-zaaktypecatalogus#24]
Wanneer ik vanuit de admin schermen voor de ztc component een statustype wil toevoegen krijg ik de volgende melding: Sorry, a server error has occurred (500)

http://10.0.75.2:8002/admin/datamodel/statustype/add/

Uit de logs van de ztc het volgende:

[pid: 20|app: 0|req: 185/692] 10.0.75.1 () {44 vars in 943 bytes} [Tue Dec  4 12:33:52 2018] POST /admin/datamodel/statustype/add/ => generated 3941 bytes in 32 msecs (HTTP/1.1 500) 4 headers in 143 bytes (1 switches on core 1)

**Comment by sergei-maertens** [comment]
This is probably related to the user-unfriendly duration-field inputs combined with a bug that has been fixed (invalid input leads to validation error, but subsequent validation assumes that the previous validation was successful, leading to `TypeError` and crashing). A fix has been introduced, definitely in the `develop` branch, and should go live with the next feature release if it's not fixed in `master` yet.

**Comment by sergei-maertens** [comment]
Fixes have been released a while ago, so please let us know if this still happens!
